apiVersion: apps/v1
kind: Deployment
metadata: 
  name: catalogue
  namespace: roboshop
  # these labels are for replica set
  labels:
    project: roboshop
    component: catalogue
    tier: backend
spec:
  replicas: 1
  selector: 
  # these labels are used to select pods
    matchLabels: 
      project: roboshop
      component: catalogue
      tier: backend
    # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: catalogue
        tier: backend 
    spec: 
      containers: 
      - name: catalogue
        image: testdockerhub28/catalogue:v1
        imagePullPolicy: Always
        readinessProbe: 
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 1 
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata: 
  name: catalogue
  namespace: roboshop
spec: 
  selector:
     project: roboshop
     component: catalogue
     tier: backend
  ports:
    - protocol: TCP
      port: 8080 #service port
      targetPort: 8080 #container port     