apiVersion: v1
kind: Service
metadata: 
  name: nginx-lb
spec: 
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    environmanet: dev
    purpose: loadbalancer
  ports: 
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port
      nodePort: 30007
