apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      request:
        memory: "68Mi"
        cpu: "100m" #1/10th of CPU
      limits:
        memory: "100Mi"
        cpu: "120m"