apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::444353257404:role/eksctl-volumes-k8-dev-nodegroup-ro-NodeInstanceRole-pqalFMWLoeoy
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::444353257404:user/suresh
      username: suresh
kind: ConfigMap

metadata:
  creationTimestamp: "2026-03-19T03:37:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1121"
  uid: 931a53a8-9e87-42d2-b155-0f1d3563bac0


