apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::444353257404:role/eksctl-volumes-k8-dev-addon-iamserviceaccount-Role1-QNrYyRMztLds
  creationTimestamp: "2026-03-19T06:10:00Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: secret-reader
  namespace: roboshop
  resourceVersion: "27455"
  uid: 2e317493-86cd-4784-91bf-690e03ca96b1
