apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: roboshop-efs-sc
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: efs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1f   # to determine the node in which we need to mount volume
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: efs-claim