apiVersion: apps/v1
kind: Deployment
metadata: 
  name: taintsandtolerations
  # these labels are for replica set
  labels:
    project: toleration-demo
    purpose: replicas 
spec:
  replicas: 3
  selector: 
  # these labels are used to select pods
    matchLabels: 
      project: toleration-demo
      purpose: replicas 
    # pod definition
  template:
    metadata:
      labels:
        project: toleration-demo
        purpose: replicas 
    spec: 
      containers: 
      - name: nginx
        image: nginx:latest