apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongodb
  namespace: roboshop
  # these labels are for replica set
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector: 
  # these labels are used to select pods
    matchLabels: 
      project: roboshop
      component: mongodb
      tier: db
    # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db 
    spec: 
      containers: 
      - name: mongodb
        image: testdockerhub28/mongodb:v1
        readinessProbe: 
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5
  ---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb
  namespace: toboshop
spec: 
  selector:
     project: roboshop
     component: mongodb
     tier: db 
  ports:
    - protocol: TCP
      port: 27017 #service port
      targetPort: 27017 #container port     